services:
- type: web
  name: hasura
  env: docker
  region: frankfurt
  plan: standard
  autoDeploy: false
  healthCheckPath: /healthz
  envVars:
  - key: HASURA_GRAPHQL_DATABASE_URL
    fromDatabase:
      name: hasura
      property: connectionString
  - key: HASURA_GRAPHQL_ENABLE_CONSOLE
    value: true
  - key: PORT
    value: 10000
  - key: HASURA_GRAPHQL_ADMIN_SECRET
    generateValue: true
databases:
- name: hasura
